-- Trigers are store programs that can automatically execute when some specific event perform
-- like delete,insert ,update, delete and etc
--benifites of trigger
-- 1 gain strong controll over security
--2 event logging and storing information on the table
